# Generated by Django 2.2.13 on 2020-08-10 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_answers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='question_id',
            new_name='question',
        ),
    ]
