# Generated by Django 2.2.13 on 2020-08-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_answers', '0003_auto_20200811_0012'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useranswer',
            table='users_answers',
        ),
    ]
