# Generated by Django 2.2.13 on 2020-08-09 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1024)),
                ('type', models.CharField(choices=[('CUSTOM', 'custom'), ('ONE', 'one'), ('MULTIPLE', 'multiple')], max_length=8)),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='topics.Topic')),
            ],
        ),
    ]
