# Generated by Django 2.2.13 on 2020-08-10 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
