# Generated by Django 2.2.13 on 2020-08-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20200810_2056'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
