# Generated by Django 2.2.13 on 2020-08-10 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='start_date',
            field=models.DateField(),
        ),
    ]
