# Generated by Django 2.2.13 on 2020-08-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20200810_0039'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='topic',
            table='topics',
        ),
    ]
